services:
  - type: web
    name: photobooth
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    branch: main
    plan: free
    runtime: python
